### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by bfred-it** [HangYang/one-click-extensions-manager#15]
1. Can you rename this repo to `one-click-extensions-manager` for consistency?
0. Can you update the screenshot on the Chrome Web Store?
0. Can you set the Website on the Chrome Web Store to point to the GitHub repo?
    
    <img width="172" alt="screen shot 2017-03-15 at 14 03 58" src="https://cloud.githubusercontent.com/assets/1402241/23937088/eba7aeb4-0912-11e7-963a-1ff256983792.png">

**Comment by HangYang** [comment]
Sure,
1 and 3 is done.
Do you have some good ideas about the screenshot?

**Comment by bfred-it** [comment]
No special ideas, but the design is now old. Do you have a retina display? It will look better

**Comment by bfred-it** [comment]
If you want I'll generate a screenshot and animation for GitHub later :)

**Comment by HangYang** [comment]
Yes, Please do it.

**Comment by bfred-it** [comment]
<img width="640" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1402241/23941743/41388790-0927-11e7-9ef0-abe4204fa5c5.png">
