### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by lpresser** [HangYang/one-click-extensions-manager#24]
So, I downloaded it. Now it's sitting up on my toolbar taking up space right alongside all the other extensions it was supposed to manage. Yeah, it's got the other extensions listed when I click on its icon. But I wanted it to hide all the icons from the other extensions, too. And it didn't. And I can't figure out how to make it hide the icons. Which is the whole entire reason I downloaded it. Any advice?

**Comment by bfred-it** [comment]
This extension disables other extensions. If you want to hide the icons there’s a “grabber” before the first icon that you can drag and hide them. Search on YouTube
