### ISSUE TITLE
Re-Open with OneClick

### ISSUE THREAD

**Issue by stefanibus** [HangYang/one-click-extensions-manager#25]
Provided we are in a situation where the USER  Clicks on "DISABLE ALL":    I wonder if  our "one-click-manager"  might be capable to remember the previously active extensions befor it closes them all?     That would enable this extension to also re-open those apps.   We might toggle the Link "DISABLE ALL"  to "Re-Open-All". 
When Re-Open-All gets called,  the app would  Re-open-all-previously active AddOns with only one Click.

 I would love to re-enable my set of previously enabled extensions with one click .  

My use-case: While developing I will disable all extensions.  Once I am done , I will  re-enable the same  number of apps again. Those are 12 apps in my case.  That requires  12 Clicks .  I wonder if this 'feature' might also cause "added value" for several other users?
  
  
Another approach to make my life easier might be to **sort the list** by state of the addon, instead of alphabetical. That means "previously enabled addons would still show up at the top of the list, and all the others below . That would certainly make the "re-enabling-process" much easier for me to complete. The longer the list, the harder it will become to reactivate just "some" addons. IF the list was sorted by State, = with the  "previously enabled addons at the top, then  those relevant addons would still need 12 clicks  to be re-enabled, but the clicking-process  would be far easier to complete.

**Comment by stefanibus** [comment]
Thank you for mentioning it!!! The ShortCut  you mentioned exactly fulfills the "REVERT-Option"  I was longing for! That shortcut   is magnificent and just what I hoped for.   I I would certainly love the already  existing "Revert-Function" to be more persistent.   So we would have to store the "list of active extensions" in local storage every time the "disable all" link gets clicked.   And we would toggle the "Disable all" link to a  "revert" link on that occasion too.     If the new  revert-button gets called, we could grab the  data from localstorage.  I would love the  revert-function to be integrated.   Good Idea to limit the storage to one hour. If the revert-link remains unused for one hour, it shall toggle back to the default "disable all" link.  That way the existing Revert-Option would still be applicable  AFTER the popup got closed. The "Revert"-Option would just be so much more valuable with local-storage!

**Comment by HangYang** [comment]
added, closed. #29
