### ISSUE TITLE
大表哥,popup.js的第121行let selectedIcon = 'icon/puzzle.svg'; 中的icon少了个s

### ISSUE THREAD

**Issue by Mr-xn** [HangYang/one-click-extensions-manager#26]
如题，icon少了个s，审查弹出内容的时候会报404错误。。。希望可以修改一下，然后在商店update一下。插件很喜欢！
PS：另外有个JavaScript问题，也是关于我在修改chrome插件时遇到的问题，想向表哥请教，如果可以，回复下我。谢谢！

**Comment by HangYang** [comment]
多谢反馈……今天晚点修复。
可是为什么是大表哥……

**Comment by Mr-xn** [comment]
@HangYang 
哈哈哈 比我厉害 就是大表哥 -_-|

**Comment by HangYang** [comment]
fixed and closed

**Comment by Mr-xn** [comment]
nice！话说 表哥的邮箱hank@momane.com 在用么？给你发邮件了 也不回我。。。
