### ISSUE TITLE
Add feature, group by category and rearrange order

### ISSUE THREAD

**Issue by tirespider** [HangYang/one-click-extensions-manager#27]
Alphabetical listing is fine if you only have 20 or 30 extensions, but beyond that you really need at least a way to group them logically and move them from one to another.  How about a fixed set of top level folders, 12 is a good number, renamable and without subfolders.  Simpler is betterer.  Let me know if it's in the works and I may reinstall it.  Other than that, the one thing that I'd like to see is a historic log of installs, uninstalls, updates and reinstalls with a date and maybe a one line field for comments.  Incidentally, if it had that feature, more users would be less likely to replace it if they wouldn't want to abandon that log that is tied to OCEM.  btw, if you ever decide it needs a new name, you might do something with this:
"OnCE & for ALL Extensions."

**Comment by bfred-it** [comment]
This extension is great because it's very simple. There are a lot others that are ugly and full of features.

**Comment by HangYang** [comment]
won't implement it.

**Comment by tirespider** [comment]
OK, let me go about asking this a different way.  What about UN-alphabetizing?  Is this doable and in keeping with your vision? If so, as a user, I'd like to be the one to decide exactly what order they appear.  The essence of my request is to be able to differentiate somehow.  And it's not just about having nice, cute category names to group them and so it doesn't have to be anything that would spoil the appearance and simplicity we see now.  If I can put them in the order I want then I know where all my OCR ext (5+) are and where my draw ext (15-20) are. As an alternative or in conjunction with unalphabetization, here are some ideas for ways that would add nothing except a right click option to apply the option:
Name of extension--prepend with single chr A-Z
Font--show extension name text in specified font
Size--assign one of 4 sizes (8,10,12,14) to extension name text
Color--extension name text in specified color.  I thought of this that would require adding a single universal color option ON/OFF, and an item specific option ### (enter 100-999).  When ON, text color of first item is at one end of the spectrum and last item is at opposite end.  Extension names in between shown as a unique color making a rainbow effect.  Changing the ### changes the order and so the color of the name text.
Shading--no universal option, just an item specific option to use one of 4 shades. For each ON shade there is an automatic complimentary OFF shade. It's just as it is now but adds option to choose one of four shadings.

Much of the reason I need some differentiation function relates to testing of extensions. I want to see at a glance those of a specific group.  But I also want to know which have been tested and which have not been tested, and which have been found acceptable and which were rejected.  You might say, just remove the extensions that are rejected since you're not going to use them anyway.  I could, but then I would forget that I had tested them before and end up repeating my past effort. They are now left there but turned off.  If an item is off I can't instantly know if that's because it is a reject or not. If I don't want to rely only on my own memory I have to document these important facts elsewhere.  This may keep your extension pristine and simple, but for a user it adds a lot of overhead that could be avoided with one right click option and a short list of choices, or just a text config file as you find in Sublime Text. In fact, if you extended it to be a package in ST that could be where the mods are done for anyone who needs to; all others would see zero changes to OCE. 

I really hope you can do something that will solve my problem. It doesn't need to bother those who don't care for the new options, but it will keep extension management at its' absolute simplest for those who do.

**Comment by klarezz** [comment]
Thanks for this promising extension. 

If I may, it would really be great to have categories (or grouping) at least. 

I'm still using [extensions-manager](https://chrome.google.com/webstore/detail/extensions-manager-aka-sw/lpleipinonnoibneeejgjnoeekmbopbc) because the categories feature is awesome. It seems broken however: new categories can't be created unless imported via a configuration file.

It would be great if you could reconsider adding the categories feature.
