### ISSUE TITLE
Enable All ?

### ISSUE THREAD

**Issue by bcsnapier** [HangYang/one-click-extensions-manager#28]
The option Disable All is very useful.
However, I would also like to see an option **Enable All**.  At the moment I need to enable each one which takes time.

**Comment by HangYang** [comment]
great idea, will add it

**Comment by smaragdus** [comment]
**Enable All** will be a time saver. I hope that this feature will be implemented soon.

**Comment by HangYang** [comment]
added, closed. #29

**Comment by smaragdus** [comment]
@HangYang 

Thank you.
