### ISSUE TITLE
Feature Request: wider screen

### ISSUE THREAD

**Issue by muescha** [HangYang/one-click-extensions-manager#31]
the popup screen is very small, it could be more width

**Comment by fregante** [comment]
Most of the extensions fit well within this size. We could make it bigger but then most of the screen would be empty. It's already too big for most:

<img width="430" alt="" src="https://user-images.githubusercontent.com/1402241/69896518-1902c480-1373-11ea-83c8-1c76d6094757.png">

**Comment by muescha** [comment]
just to compare ... thats my scree:

![Bildschirmfoto 2019-11-30 um 07 31 17](https://user-images.githubusercontent.com/184316/69896804-767f1d00-1343-11ea-9d99-a086b6328576.png)

**Comment by fregante** [comment]
It still looks fine too me. FreshStart is the only one that exceeds it and it's only because they are using an unnecessarily-long name.

**Comment by muescha** [comment]
with menu ... i found how to show the menu (right click)

![Bildschirmfoto 2019-11-30 um 07 31 30](https://user-images.githubusercontent.com/184316/69896859-f4dbbf00-1343-11ea-90cd-845487c90f60.png)

**Comment by fregante** [comment]
@muescha Option added 🎉 in the upcoming version https://github.com/hankxdev/one-click-extensions-manager/releases/tag/23.3.19
