### ISSUE TITLE
Feature Request: Save current active Plugins as Set

### ISSUE THREAD

**Issue by muescha** [HangYang/one-click-extensions-manager#33]
## Current:

- just now i can only enable, disable plugins on-by-one
- this takes long time if i have many plugins

## Expected:

Some sort of favorites list

- when i have disabled/enabled some of my plugins:
  - then i can click on an "save as..."  icon
  - i can set a favorites list name

- when i have favorites list
  - the new favorites list name is visible at the top of the plugin list ordered by name

- when i have favorites lists:
  - i can hit a delete icon to delete a bookmark list
  - i can click on a bookmark list

- when i click on a bookmark list:
  - all remembered plugins are enabled, 
  - other are disabled, 
  - the bookmark list becomes bold

- if i changed the list of plugins, then:
  - a bookmark list is unbold, when the list is different from the current active plugins
  - a set name is bold, when the list is equal to the current list of active plugins

- after changing the plugin states
  - a save icon appear near each bookmark list and i can save and overwrite the this bookmark list with the current active plugins 
  - or i create a new bookmark list with the "save as.." icon

**Comment by fregante** [comment]
There are other complex extensions you can choose from; this one is meant to be simple

**Comment by muescha** [comment]
can you point me to an extension which has this feature?

**Comment by fregante** [comment]
https://chrome.google.com/webstore/detail/extensions-manager-aka-sw/lpleipinonnoibneeejgjnoeekmbopbc

It's shown in the first few seconds of the introduction video, they call it "Groups"

**Comment by muescha** [comment]
thx a lot :)
